version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    rebase-strategy: auto
    security-updates: true
