apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-metrics-adapter
  namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'container_cpu_usage_seconds_total{container!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "^(.*)_total$"
          as: "${1}_usage"
        metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
