version: '3.8'

services:

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:2.13.0-pg15
    environment:
      POSTGRES_DB: yosai_intel
      POSTGRES_USER: postgres
    secrets:
      - db_password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./scripts/init_timescaledb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
      - timescaledb
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8081:8080"
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=8080"
      - "prometheus.path=/metrics"
    environment:
      SERVICE_REGISTRY_URL: http://service-registry:8500
    depends_on:
      - analytics-service
      - service-registry
    restart: unless-stopped

  event-ingestion:
    build:
      context: ./yosai_intel_dashboard/src/services/event-ingestion
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SERVICE_REGISTRY_URL: http://service-registry:8500
    depends_on:
      - service-registry
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "uvicorn", "services.analytics_microservice.app:app", "--host", "0.0.0.0", "--port", "8001"]
    environment:
      YOSAI_ENV: development
      SERVICE_REGISTRY_URL: http://service-registry:8500
    depends_on:
      - service-registry
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    restart: unless-stopped

  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api-gateway
      - event-ingestion
      - service-registry
    restart: unless-stopped

  zookeeper:
    extends:
      file: docker-compose.kafka.yml
      service: zookeeper

  kafka1:
    extends:
      file: docker-compose.kafka.yml
      service: kafka1

  kafka2:
    extends:
      file: docker-compose.kafka.yml
      service: kafka2

  kafka3:
    extends:
      file: docker-compose.kafka.yml
      service: kafka3

  schema-registry:
    extends:
      file: docker-compose.kafka.yml
      service: schema-registry

  kafka-init:
    extends:
      file: docker-compose.kafka.yml
      service: kafka-init

  kafka-ui:
    extends:
      file: docker-compose.kafka.yml
      service: kafka-ui

  service-registry:
    image: consul:1.15
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    restart: unless-stopped

volumes:
  timescaledb_data:
  pgadmin_data:
  redis_data:

secrets:
  db_password:
    file: ./secrets/db_password
  secret_key:
    file: ./secrets/secret_key

networks:
  default:
    name: yosai-network
