services:
  api:
    command: []
    entrypoint: ["python","-m","uvicorn","wsgi:app","--host","0.0.0.0","--port","8000"]
    ports:
      - "8000:8000"

  dashboard:
    command: []
    entrypoint: ["python","-m","uvicorn","wsgi:app","--host","0.0.0.0","--port","8050"]
    ports:
      - "8050:8050"
