services:
  dashboard:
    command: ["bash","-lc","python -c \"from yosai_intel_dashboard.src.app import app; app.run_server(host='0.0.0.0', port=8050, debug=True)\""]
    env_file: [./local.env]
    environment:
      DB_USER: ${DB_USER:-devuser}
      DB_PASSWORD: ${DB_PASSWORD:-devpass}
    healthcheck:
      test: ["CMD-SHELL","true"]

  api:
    env_file: [./local.env]
    environment:
      DB_USER: ${DB_USER:-devuser}
      DB_PASSWORD: ${DB_PASSWORD:-devpass}
    healthcheck:
      test: ["CMD-SHELL","true"]
