version: "3.8"

services:
  dashboard:
    environment:
      FLASK_DEBUG: "1"
      LOG_LEVEL: "DEBUG"
    ports:
      - "5678:5678"
    volumes:
      - .:/app

  analytics-service:
    environment:
      LOG_LEVEL: "DEBUG"
    ports:
      - "5679:5678"
    volumes:
      - .:/app
