version: '3.8'

services:

  service-registry:
    image: consul:1.15
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    restart: unless-stopped

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "uvicorn", "services.analytics_microservice.app:app", "--host", "0.0.0.0", "--port", "8001"]
    environment:
      YOSAI_ENV: production
      SERVICE_REGISTRY_URL: http://service-registry:8500
      PERFORMANCE_PROFILING_ENABLED: ${PERFORMANCE_PROFILING_ENABLED:-false}
    depends_on:
      - service-registry
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8081:8080"
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=8080"
      - "prometheus.path=/metrics"
    environment:
      SERVICE_REGISTRY_URL: http://service-registry:8500
      PERFORMANCE_PROFILING_ENABLED: ${PERFORMANCE_PROFILING_ENABLED:-false}
    depends_on:
      - analytics-service
      - service-registry
    restart: unless-stopped
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yosai_intel
      POSTGRES_USER: postgres
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password
  secret_key:
    file: ./secrets/secret_key
  auth0_client_id:
    file: ./secrets/auth0_client_id
  auth0_client_secret:
    file: ./secrets/auth0_client_secret
  auth0_domain:
    file: ./secrets/auth0_domain
  auth0_audience:
    file: ./secrets/auth0_audience
