services:
  dashboard:
    command: ["bash","-lc","python -c \"from yosai_intel_dashboard.src.app import app; app.run_server(host='0.0.0.0', port=8050, debug=True)\""]
    healthcheck:
      test: ["CMD-SHELL","true"]
      interval: 30s
      timeout: 3s
      retries: 1

  api:
    healthcheck:
      test: ["CMD-SHELL","true"]
      interval: 30s
      timeout: 3s
      retries: 1
