#!/usr/bin/env python3
"""Fix app factory page registration timing"""

print("EDIT core/app_factory/__init__.py in the create_app() function:")
print("")
print("FIND this section (around line where _register_pages() is called):")
print("  _register_pages()  # ❌ This happens before app creation")
print("  ")
print("  app = dash.Dash(")
print("      __name__,")
print("      external_stylesheets=external_stylesheets,")
print("      suppress_callback_exceptions=True,")
print("      assets_folder=assets_folder,")
print("      assets_ignore=assets_ignore,")
print("      use_pages=False,")
print("      pages_folder=\"\",")
print("  )")
print("")
print("MOVE _register_pages() to AFTER app creation:")
print("  app = dash.Dash(")
print("      __name__,")
print("      external_stylesheets=external_stylesheets,")
print("      suppress_callback_exceptions=True,")
print("      assets_folder=assets_folder,")
print("      assets_ignore=assets_ignore,")
print("      use_pages=False,")
print("      pages_folder=\"\",")
print("  )")
print("  ")
print("  _register_pages()  # ✅ Now after app exists")
