[tool.mypy]
python_version = "3.11"
explicit_package_bases = true
mypy_path = ["."]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = [
    "core",
    "models",
    "services",
    "analytics",
    "analyzers",
    "components",
    "pages",
    "utils",
]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '(\.pyi?|\.ipynb)$'
exclude = '/(\.direnv|\.eggs|\.git|\.hg|\.ipynb_checkpoints|\.mypy_cache|\.nox|\.pytest_cache|\.ruff_cache|\.tox|\.svn|\.venv|\.vscode|__pypackages__|_build|buck-out|build|dist|venv)/'
