openapi: 3.0.2
info:
  title: Access Event Service
  version: 1.0.0
paths:
  /v1/events:
    post:
      summary: Submit an access event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessEvent'
      responses:
        '200':
          description: Acknowledgement
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventResponse"
          description: Acknowledgement
      summary: Submit an access event
  /v1/events/batch:

    post:
      summary: Submit a batch of access events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_v1_events_batch_post_request"
        required: true

      responses:
        '200':
          description: Batch status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_v1_events_batch_post_200_response"
          description: Batch status
      summary: Submit a batch of access events

components:
  schemas:
    AccessEvent:
      type: object
      properties:
        event_id:
          type: string
        timestamp:
          type: string
          format: date-time
        person_id:
          type: string
          nullable: true
        door_id:
          type: string
          nullable: true
        badge_id:
          type: string
          nullable: true
        access_result:
          type: string
        badge_status:
          type: string
          nullable: true
        door_held_open_time:
          type: number
          format: double
          nullable: true
        entry_without_badge:
          type: boolean
          nullable: true
        device_status:
          type: string
          nullable: true
      required:
        - event_id
        - timestamp
        - access_result
    EventResponse:
      type: object
      properties:
        event_id:
          type: string
        status:
          type: string
      required:
      - event_id
      - status
      type: object
    _v1_events_batch_post_request:
      properties:
        events:
          items:
            $ref: "#/components/schemas/AccessEvent"
          type: array
      type: object
    _v1_events_batch_post_200_response:
      example:
        results:
        - event_id: event_id
          status: status
        - event_id: event_id
          status: status
      properties:
        results:
          items:
            $ref: "#/components/schemas/EventResponse"
          type: array
      type: object
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
        details:
          nullable: true
          type: string
      required:
      - code
      - message

