receivers:
  otlp:
    protocols:
      http:

exporters:
  otlp:
    # The upstream collector or tracing backend endpoint.
    endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
