receivers:
  otlp:
    protocols:
      http:

exporters:
  otlp:
    endpoint: ${OTEL_COLLECTOR_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
