apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-service-secret
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: yosai-microservices
    app.kubernetes.io/component: analytics
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: analytics-service-secret
  data:
    - secretKey: ANALYTICS_DB_PASSWORD
      remoteRef:
        key: secret/data/analytics-service
        property: ANALYTICS_DB_PASSWORD
