apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secret
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: yosai-microservices
    app.kubernetes.io/component: gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-gateway-secret
  data:
    - secretKey: API_GATEWAY_TOKEN
      remoteRef:
        key: secret/data/api-gateway
        property: API_GATEWAY_TOKEN
