[project]
name = "analytics-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["fastapi", "uvicorn"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
