version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infra

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - infra

  vault:
    image: hashicorp/vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID:-root}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:${VAULT_PORT:-8200}
    ports:
      - "${VAULT_PORT:-8200}:${VAULT_PORT:-8200}"
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    networks:
      - infra

    kafka:
      image: redpandadata/redpanda:${REDPANDA_TAG:-23.2.4}

    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --check=false
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    volumes:
      - kafka_data:/var/lib/redpanda/data
    networks:
      - infra

networks:
  infra:

volumes:
  postgres_data:
  redis_data:
  kafka_data:
