version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/yosai_intel
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yosai_intel
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: integration-secret
      AUTH0_CLIENT_ID: dummy
      AUTH0_CLIENT_SECRET: dummy
      AUTH0_DOMAIN: example.com
      AUTH0_AUDIENCE: dummy
      JWT_SECRET: dummy
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yosai_intel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
