info:
  title: Yosai Dashboard API
  version: 1.0.0
openapi: 3.0.2
paths:
  /v1/ai/suggest-devices:
    options:
      description: Suggest device mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404':
          $ref: '#/components/responses/File not found'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - device
    post:
      description: Suggest device mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404':
          $ref: '#/components/responses/File not found'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - device
  /v1/mappings/columns:
    options:
      description: Save column mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/Invalid input'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
    post:
      description: Save column mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/Invalid input'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
  /v1/mappings/devices:
    options:
      description: Save device mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/Invalid input'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
    post:
      description: Save device mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/Invalid input'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
  /v1/mappings/save:
    options:
      description: Save mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
    post:
      description: Save mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
  /v1/process-enhanced:
    options:
      description: Process data with mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404':
          $ref: '#/components/responses/Not Found'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
    post:
      description: Process data with mappings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404':
          $ref: '#/components/responses/Not Found'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - mappings
  /v1/settings:
    get:
      description: Get user settings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
      tags:
      - settings
    options:
      description: Update user settings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - settings
    post:
      description: Update user settings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - settings
    put:
      description: Update user settings
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - settings
  /v1/token/refresh:
    options:
      description: Refresh access token
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '401':
          $ref: '#/components/responses/Unauthorized'
      tags:
      - token
    post:
      description: Refresh access token
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '401':
          $ref: '#/components/responses/Unauthorized'
      tags:
      - token
  /v1/upload:
    options:
      description: Upload a file
      parameters: []
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          $ref: '#/components/responses/Invalid CSRF token'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - upload
    post:
      description: Upload a file
      parameters: []
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          $ref: '#/components/responses/Invalid CSRF token'
        '500':
          $ref: '#/components/responses/Server Error'
      tags:
      - upload
  /v1/upload/status/{job_id}:
    get:
      parameters:
      - description: Upload job id
        in: path
        name: job_id
        required: true
        schema:
          type: string
        type: string
      responses:
        '200':
          $ref: '#/components/responses/Success'
      tags:
      - upload
    options:
      parameters:
      - description: Upload job id
        in: path
        name: job_id
        required: true
        schema:
          type: string
        type: string
      responses:
        '200':
          $ref: '#/components/responses/Success'
      tags:
      - upload

