apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          app
    [OUTPUT]
        Name  es
        Match *
        Host  ${ELASTICSEARCH_HOST}
        Port  9200
        Index gateway
    [OUTPUT]
        Name  datadog
        Match *
        Host  ${DATADOG_HOST}
        TLS   On
        Apikey ${DATADOG_API_KEY}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config

