apiVersion: v1
kind: Secret
metadata:
  name: dashboard-api-secrets
  namespace: yosai-dev
  annotations:
    linkerd.io/inject: enabled
type: Opaque
stringData:
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
