apiVersion: v1
kind: Secret
metadata:
  name: dashboard-api-secrets
  namespace: yosai-dev
type: Opaque
stringData:
  AUTH0_CLIENT_ID: "vault:secret/data/${YOSAI_ENV}/auth0#client_id"
  AUTH0_CLIENT_SECRET: "vault:secret/data/${YOSAI_ENV}/auth0#client_secret"
