apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yosai-intel.fullname" . }}
  labels:
    {{- include "yosai-intel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "yosai-intel.labels" . | nindent 8 }}
      annotations:
        {{- range $key, $val := .Values.podAnnotations }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "yosai-intel.serviceAccountName" . }}
      initContainers:
        - name: setup-symlinks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "scripts/create_symlinks.py"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PYTHONPATH
              value: {{ .Values.pythonPath | quote }}
            - name: MODULE_PATH
              value: {{ .Values.modulePath | quote }}
            - name: ENABLE_LEGACY_IMPORTS
              value: {{ .Values.enableLegacyImports | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup }}
              port: {{ .Values.service.port }}
            failureThreshold: 30
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
