global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8050']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
