# Configuration overrides to support post-deployment penetration testing
logging:
  level: debug
  enable_http_headers: true
security:
  rate_limit_per_minute: 1000  # relaxed for testing
  allow_test_accounts: true
