stages:
  - build
  - canary
  - blue_green

build:
  stage: build
  script:
    - docker build -t yosai-dashboard:$CI_COMMIT_SHA .

canary:
  stage: canary
  script:
    - kubectl apply -f k8s/canary
  when: manual
  needs:
    - build

blue_green:
  stage: blue_green
  script:
    - kubectl apply -f k8s/bluegreen
  when: manual
  needs:
    - canary
