stages:
  - build
  - canary
  - traffic_shift
  - blue_green

variables:
  TARGET_ENV: "staging"
  TRAFFIC_PERCENT: "10"

build:
  stage: build
  script:
    - docker build -t yosai-dashboard:$CI_COMMIT_SHA .

canary:
  stage: canary
  script:
    - TARGET_ENV=$TARGET_ENV TRAFFIC_PERCENT=$TRAFFIC_PERCENT \
      deployment/scripts/traffic_shape.sh
  when: manual
  needs:
    - build

traffic_shift:
  stage: traffic_shift
  script:
    - TARGET_ENV=$TARGET_ENV TRAFFIC_PERCENT=50 \
      deployment/scripts/traffic_shape.sh
  when: manual
  needs:
    - canary

blue_green:
  stage: blue_green
  script:
    - kubectl apply -f k8s/bluegreen
  when: manual
  needs:
    - traffic_shift
