variables:
  DEPLOY_ENV: "staging"
  TRAFFIC_PERCENT: "10"
  STATEFUL_SERVICE: "dashboard-db"

stages:
  - build
  - canary
  - traffic_shaping
  - verify_stateful
  - blue_green

build:
  stage: build
  script:
    - docker build -t yosai-dashboard:$CI_COMMIT_SHA .

canary:
  stage: canary
  script:
    - kubectl --context $DEPLOY_ENV apply -f k8s/canary
  when: manual
  needs:
    - build

traffic_shaping:
  stage: traffic_shaping
  script:
    - deployment/scripts/traffic_shaping.sh
  when: manual
  needs:
    - canary

verify_stateful:
  stage: verify_stateful
  script:
    - deployment/scripts/verify_stateful.sh $STATEFUL_SERVICE
  when: manual
  needs:
    - traffic_shaping

blue_green:
  stage: blue_green
  script:
    - kubectl --context $DEPLOY_ENV apply -f k8s/bluegreen
  when: manual
  needs:
    - verify_stateful
