/* tslint:disable */
/* eslint-disable */
/**
 * Yōsai Intel Dashboard API
 * Physical security intelligence and access control API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCsrfToken200Response
 */
export interface GetCsrfToken200Response {
    /**
     * 
     * @type {string}
     * @memberof GetCsrfToken200Response
     */
    csrfToken?: string;
}

/**
 * Check if a given object implements the GetCsrfToken200Response interface.
 */
export function instanceOfGetCsrfToken200Response(value: object): value is GetCsrfToken200Response {
    return true;
}

export function GetCsrfToken200ResponseFromJSON(json: any): GetCsrfToken200Response {
    return GetCsrfToken200ResponseFromJSONTyped(json, false);
}

export function GetCsrfToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCsrfToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'csrfToken': json['csrf_token'] == null ? undefined : json['csrf_token'],
    };
}

export function GetCsrfToken200ResponseToJSON(json: any): GetCsrfToken200Response {
    return GetCsrfToken200ResponseToJSONTyped(json, false);
}

export function GetCsrfToken200ResponseToJSONTyped(value?: GetCsrfToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csrf_token': value['csrfToken'],
    };
}

