@startuml
class BaseComponent
class WebSocketDataProvider
BaseComponent <|-- WebSocketDataProvider

interface ConfigProvider
class ConfigService
ConfigProvider <|.. ConfigService

interface EventBusProtocol
class EventBus
EventBus ..|> EventBusProtocol
@enduml
