@startuml
interface IPersonRepository
class PersonRepository
class InMemoryPersonRepository
IPersonRepository <|.. PersonRepository
IPersonRepository <|.. InMemoryPersonRepository

interface IAccessEventRepository
class AccessEventRepository
IAccessEventRepository <|.. AccessEventRepository

interface IDoorRepository
class DoorRepository
IDoorRepository <|.. DoorRepository
@enduml
