# Example circuit breaker settings for Go services

database:
  failure_threshold: 5
  recovery_timeout: 30  # seconds

external_api:
  failure_threshold: 3
  recovery_timeout: 15

event_processor:
  failure_threshold: 10
  recovery_timeout: 60
