app:
  title: "Yosai Intelligence Dashboard"
  debug: false
  host: "0.0.0.0"
  port: ${PORT:8050}
  log_level: ${LOG_LEVEL:INFO}
  enable_profiling: ${ENABLE_PROFILING:false}

database:
  type: postgresql
  host: ${DB_HOST}
  port: ${DB_PORT:5432}
  # Individual DB names for microservices
  gateway_name: ${DB_GATEWAY_NAME:yosai_gateway_db}
  events_name: ${DB_EVENTS_NAME:yosai_events_db}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: vault:secret/data/db#password
  url: ${DATABASE_URL:}
  initial_pool_size: ${DB_INITIAL_POOL_SIZE:10}
  max_pool_size: ${DB_MAX_POOL_SIZE:20}
  connection_timeout: ${DB_TIMEOUT:30}
  shrink_timeout: ${DB_SHRINK_TIMEOUT:60}
  retry_attempts: ${DB_RETRY_ATTEMPTS:3}

cache:
  type: redis
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  database: ${REDIS_DB:0}
  timeout_seconds: ${CACHE_TIMEOUT:600}
  key_prefix: ${CACHE_PREFIX:yosai:prod:}
  compression_enabled: ${CACHE_COMPRESSION:true}
  max_memory_mb: ${CACHE_MAX_MEMORY_MB:100}

security:
  secret_key: vault:secret/data/app#secret_key
  session_timeout_minutes: ${SESSION_TIMEOUT:30}
  max_file_size_mb: ${MAX_FILE_SIZE:50}
  max_upload_mb: ${MAX_UPLOAD_MB:500}
  max_analysis_mb: ${MAX_ANALYSIS_MB:1000}
  allowed_file_types:
    - .csv
    - .json
    - .xlsx
    - .xls
  cors_enabled: ${CORS_ENABLED:true}
  cors_origins:
    - ${FRONTEND_URL:https://dashboard.yourdomain.com}
    - ${API_URL:https://api.yourdomain.com}
  rate_limiting_enabled: ${RATE_LIMITING:true}
  rate_limit_per_minute: ${RATE_LIMIT:120}

analytics:
  cache_timeout_seconds: ${ANALYTICS_CACHE_TIMEOUT:600}
  max_records_per_query: ${MAX_QUERY_RECORDS:50000}
  enable_real_time: ${ENABLE_REAL_TIME:true}
  batch_size: ${BATCH_SIZE:5000}
  chunk_size: ${ANALYTICS_CHUNK_SIZE:100000}
  max_workers: ${ANALYTICS_MAX_WORKERS:4}
  enable_chunked_analysis: ${ENABLE_CHUNKED_ANALYSIS:true}
  anomaly_detection_enabled: ${ENABLE_ANOMALY_DETECTION:true}
  ml_models_path: ${ML_MODELS_PATH:models/ml}
  data_retention_days: ${DATA_RETENTION_DAYS:365}
  query_timeout_seconds: ${QUERY_TIMEOUT_SECONDS:600}
  force_full_dataset_analysis: ${FORCE_FULL_DATASET:true}
  max_display_rows: ${MAX_DISPLAY_ROWS:10000}
  row_limit_warning: ${ROW_LIMIT_WARNING:150}
  large_data_threshold: ${LARGE_DATA_THRESHOLD:1000}

monitoring:
  health_check_enabled: true
  metrics_enabled: true
  health_check_interval: ${HEALTH_CHECK_INTERVAL:30}
  performance_monitoring: ${ENABLE_PERFORMANCE_MONITORING:true}
  memory_threshold_mb: ${MEMORY_THRESHOLD_MB:1024}
  error_reporting_enabled: ${ENABLE_ERROR_REPORTING:true}
  sentry_dsn: ${SENTRY_DSN}
  log_retention_days: ${LOG_RETENTION_DAYS:90}

uploads:
  chunk_size: ${UPLOAD_CHUNK_SIZE:50000}
  max_parallel_uploads: ${MAX_PARALLEL_UPLOADS:4}
  validator_rules:
    sql_injection: true
    xss: true
    path_traversal: true

streaming:
  service_type: ${STREAMING_SERVICE:kafka}
  brokers: ${STREAMING_BROKERS:localhost:9092}
  topic: ${STREAMING_TOPIC:events}
  consumer_group: ${STREAMING_CONSUMER_GROUP:yosai}

secret_validation:
  severity: high
