# Minimal Yosai Configuration
app:
  title: "Yosai Intelligence Dashboard"
  debug: false
  host: "127.0.0.1"
  port: 8050
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  name: "yosai_db"
  user: "yosai_user"
  password: "${DB_PASSWORD}"

security:
  secret_key: "${SECRET_KEY}"
  session_timeout: 3600

sample_files:
  csv_path: "data/sample_data.csv"
  json_path: "data/sample_data.json"

analytics:
  enabled: true
  batch_size: 100

monitoring:
  health_check_interval: 30
  metrics_enabled: true

cache:
  type: "memory"
  ttl: 300
