# Minimal Yosai Configuration
app:
  title: "Yosai Intelligence Dashboard"
  debug: false
  host: "127.0.0.1"
  port: 8050
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  name: "yosai_db"
  user: "yosai_user"
  password: "${DB_PASSWORD}"

security:
  secret_key: "${SECRET_KEY}"
  session_timeout_minutes: 120
  max_file_size_mb: 250
  max_upload_mb: 500
  max_analysis_mb: 1000
  allowed_file_types:
    - .csv
    - .json
    - .xlsx
    - .xls
  cors_enabled: false
  cors_origins: []
  rate_limiting_enabled: false
  rate_limit_per_minute: 1000

sample_files:
  csv_path: "data/sample_data.csv"
  json_path: "data/sample_data.json"

analytics:
  cache_timeout_seconds: 60
  max_records_per_query: 2000000  # see DataProcessingLimits.MAX_DATAFRAME_PROCESSING_ROWS_ROWS
  enable_real_time: true
  batch_size: 25000
  chunk_size: 100000
  enable_chunked_analysis: true
  anomaly_detection_enabled: true
  ml_models_path: models/ml
  data_retention_days: 30
  query_timeout_seconds: 600
  force_full_dataset_analysis: true

monitoring:
  health_check_interval: 30
  metrics_enabled: true

cache:
  type: "memory"
  ttl: 300
