# Minimal Yosai Configuration
app:
  title: "Yosai Intelligence Dashboard"
  debug: true
  host: "127.0.0.1"
  port: 8051
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  name: "yosai_db"
  user: "yosai_user"
  password: "${DB_PASSWORD}"

security:
  secret_key: "${SECRET_KEY}"
  session_timeout: 3600

sample_files:
  csv_path: "data/sample_data.csv"
  json_path: "data/sample_data.json"

analytics:
  enabled: true
  batch_size: 25000
  max_records_per_query: 500000
  chunk_size: 50000
  force_full_dataset_analysis: true
  query_timeout_seconds: 300

monitoring:
  health_check_interval: 30
  metrics_enabled: true

cache:
  type: "memory"
  ttl: 300
