apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-critical-rules
  labels:
    release: prometheus
spec:
  groups:
    - name: service.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total[5m])) > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: CPU usage above 90%
            description: High CPU usage detected
        - alert: HighMemoryUsage
          expr: sum(container_memory_usage_bytes) / sum(container_spec_memory_limit_bytes) > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Memory usage above 90%
            description: High memory usage detected
        - alert: HighErrorRate
          expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Error rate above 5%
            description: High error rate detected
