gateway:
  plugins:
    - name: rate-limit
      enabled: true
      config:
        rules:
          - path: /api/v1/events
            limit_per_min: 100
            burst_size: 20
    - name: cache
      enabled: true
      config:
        rules:
          - path: /api/v1/analytics
            ttl: 300s
            vary_headers: [Authorization]
            vary_params: [user]
            invalidate_paths:
              - /api/v1/analytics/update
  queue:
    type: rabbitmq
    url: amqp://rabbitmq:5672
