apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: yosai-microservices
    app.kubernetes.io/component: analytics
data:
  LOG_LEVEL: "INFO"
  ANALYTICS_BATCH_SIZE: "100"
