apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: yosai-microservices
    app.kubernetes.io/component: gateway
data:
  LOG_LEVEL: "INFO"
