apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-rotation
spec:
  schedule: "0 3 1 */3 *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rotate-secrets
              image: yosai-intel-dashboard:latest
              command: ["python", "scripts/vault_rotate.py"]
              envFrom:
                - configMapRef:
                    name: vault-config
                - secretRef:
                    name: vault-secret
