apiVersion: batch/v1
kind: CronJob
metadata:
  name: timescale-replication
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: replicate-to-timescale
              image: yosai-intel-dashboard:latest
              command: ["python", "scripts/replicate_to_timescale.py"]
              envFrom:
                - configMapRef:
                    name: yosai-config
                - configMapRef:
                    name: vault-config
                - secretRef:
                    name: vault-secret

