apiVersion: v1
kind: Secret
metadata:
  name: timescale-dsns
  namespace: yosai-dev
stringData:
  SOURCE_DSN: postgresql://yosai_user:change-me@postgres:5432/yosai_intel
  TARGET_DSN: postgresql://postgres:change-me@timescaledb:5432/yosai_timescale

