apiVersion: batch/v1
kind: CronJob
metadata:
  name: timescale-replication
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: replicate-to-timescale
              image: yosai-intel-dashboard:${IMAGE_TAG:-v0.1.0}
              imagePullPolicy: IfNotPresent
              command: ["python", "scripts/replicate_to_timescale.py"]
              envFrom:
                - configMapRef:
                    name: yosai-config
                - configMapRef:
                    name: vault-config
                - secretRef:
                    name: vault-secret

