apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-rotate
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: rotate-secrets
              image: yosai-intel-dashboard:${IMAGE_TAG:-v0.1.0}
              imagePullPolicy: IfNotPresent
              command: ["python", "scripts/vault_rotate.py"]
              envFrom:
                - configMapRef:
                    name: vault-config
                - secretRef:
                    name: vault-secret
