apiVersion: v2
name: yosai-intel
description: Helm chart for the Yōsai Intel Dashboard
version: 0.2.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 16.7.21
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 21.2.13
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 32.3.10
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
