replicaCount: 2

image:
  repository: yosai-intel-dashboard
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8050

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "true"

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

pythonPath: "/app:/app/yosai_intel_dashboard/src"
modulePath: "yosai_intel_dashboard.src.services.main"
enableLegacyImports: "true"
probes:
  liveness: "/health/live"
  readiness: "/health/ready"
  startup: "/health/startup"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70
  targetMemory: 75

podDisruptionBudget:
  enabled: true
  minAvailable: 1

verticalPodAutoscaler:
  enabled: false
  updatePolicy:
    updateMode: Auto

networkPolicy:
  enabled: false
  allowNamespace: ""
