apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yosai-intel-dashboard-staging
spec:
  project: default
  source:
    repoURL: https://github.com/WSG23/yosai_intel_dashboard_fresh.git
    path: k8s/staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
