apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: network-loss
  namespace: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: ['']
        resources: ['pods']
        verbs: ['get','list','patch']
    image: litmuschaos/go-runner:2.14.0
    args:
      - -c
      - |
        ./experiments -name network-loss
    env:
      - name: TOTAL_CHAOS_DURATION
        value: '60'
      - name: NETWORK_PACKET_LOSS_PERCENTAGE
        value: '100'
