apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: cpu-hog
  namespace: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: ['']
        resources: ['pods']
        verbs: ['get','list','patch']
    image: litmuschaos/go-runner:2.14.0
    args:
      - -c
      - |
        ./experiments -name cpu-hog
    env:
      - name: TOTAL_CHAOS_DURATION
        value: '60'
      - name: CPU_CORE
        value: '2'
