/*
Yōsai Intel Dashboard API

Physical security intelligence and access control API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCsrfToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCsrfToken200Response{}

// GetCsrfToken200Response struct for GetCsrfToken200Response
type GetCsrfToken200Response struct {
	CsrfToken *string `json:"csrf_token,omitempty"`
}

// NewGetCsrfToken200Response instantiates a new GetCsrfToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCsrfToken200Response() *GetCsrfToken200Response {
	this := GetCsrfToken200Response{}
	return &this
}

// NewGetCsrfToken200ResponseWithDefaults instantiates a new GetCsrfToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCsrfToken200ResponseWithDefaults() *GetCsrfToken200Response {
	this := GetCsrfToken200Response{}
	return &this
}

// GetCsrfToken returns the CsrfToken field value if set, zero value otherwise.
func (o *GetCsrfToken200Response) GetCsrfToken() string {
	if o == nil || IsNil(o.CsrfToken) {
		var ret string
		return ret
	}
	return *o.CsrfToken
}

// GetCsrfTokenOk returns a tuple with the CsrfToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCsrfToken200Response) GetCsrfTokenOk() (*string, bool) {
	if o == nil || IsNil(o.CsrfToken) {
		return nil, false
	}
	return o.CsrfToken, true
}

// HasCsrfToken returns a boolean if a field has been set.
func (o *GetCsrfToken200Response) HasCsrfToken() bool {
	if o != nil && !IsNil(o.CsrfToken) {
		return true
	}

	return false
}

// SetCsrfToken gets a reference to the given string and assigns it to the CsrfToken field.
func (o *GetCsrfToken200Response) SetCsrfToken(v string) {
	o.CsrfToken = &v
}

func (o GetCsrfToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCsrfToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CsrfToken) {
		toSerialize["csrf_token"] = o.CsrfToken
	}
	return toSerialize, nil
}

type NullableGetCsrfToken200Response struct {
	value *GetCsrfToken200Response
	isSet bool
}

func (v NullableGetCsrfToken200Response) Get() *GetCsrfToken200Response {
	return v.value
}

func (v *NullableGetCsrfToken200Response) Set(val *GetCsrfToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCsrfToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCsrfToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCsrfToken200Response(val *GetCsrfToken200Response) *NullableGetCsrfToken200Response {
	return &NullableGetCsrfToken200Response{value: val, isSet: true}
}

func (v NullableGetCsrfToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCsrfToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
