groups:
- name: service-alerts
  rules:
  - alert: HighRequestLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
    for: 5m
    labels:
      severity: page
    annotations:
      summary: 95th percentile latency > 500ms
  - alert: HighErrorRate
    expr: rate(http_requests_total{code=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
    for: 5m
    labels:
      severity: page
    annotations:
      summary: Error rate >5%
  - alert: KafkaConsumerLag
    expr: kafka_consumergroup_lag > 1000
    for: 10m
    labels:
      severity: page
    annotations:
      summary: Kafka consumer lag > 1000 messages
