apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary
spec:
  selector:
    app: {{ .Release.Name }}
    track: canary
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
