# coding: utf-8

"""
    Access Event Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_events_batch_post_request import V1EventsBatchPostRequest

class TestV1EventsBatchPostRequest(unittest.TestCase):
    """V1EventsBatchPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EventsBatchPostRequest:
        """Test V1EventsBatchPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EventsBatchPostRequest`
        """
        model = V1EventsBatchPostRequest()
        if include_optional:
            return V1EventsBatchPostRequest(
                events = [
                    {"device_status":"device_status","event_id":"event_id","entry_without_badge":true,"door_id":"door_id","badge_id":"badge_id","badge_status":"badge_status","access_result":"access_result","door_held_open_time":0.8008281904610115,"timestamp":"2000-01-23T04:56:07.000+00:00","person_id":"person_id"}
                    ]
            )
        else:
            return V1EventsBatchPostRequest(
        )
        """

    def testV1EventsBatchPostRequest(self):
        """Test V1EventsBatchPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
