# coding: utf-8

"""
    Access Event Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_events_batch_post200_response import (
    V1EventsBatchPost200Response,
)


class TestV1EventsBatchPost200Response(unittest.TestCase):
    """V1EventsBatchPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EventsBatchPost200Response:
        """Test V1EventsBatchPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EventsBatchPost200Response`
        """
        model = V1EventsBatchPost200Response()
        if include_optional:
            return V1EventsBatchPost200Response(
                results = [
                    {"event_id":"event_id","status":"status"}
                    ]
            )
        else:
            return V1EventsBatchPost200Response(
        )
        """

    def testV1EventsBatchPost200Response(self):
        """Test V1EventsBatchPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
