# coding: utf-8

"""
    Access Event Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_events_batch_post(self) -> None:
        """Test case for api_v1_events_batch_post

        Submit a batch of access events
        """
        pass

    def test_api_v1_events_post(self) -> None:
        """Test case for api_v1_events_post

        Submit an access event
        """
        pass


if __name__ == '__main__':
    unittest.main()
