# coding: utf-8

"""
    Access Event Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_v1_events_batch_post200_response import (
    ApiV1EventsBatchPost200Response,
)


class TestApiV1EventsBatchPost200Response(unittest.TestCase):
    """ApiV1EventsBatchPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1EventsBatchPost200Response:
        """Test ApiV1EventsBatchPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1EventsBatchPost200Response`
        """
        model = ApiV1EventsBatchPost200Response()
        if include_optional:
            return ApiV1EventsBatchPost200Response(
                results = [
                    openapi_client.models.event_response.EventResponse(
                        event_id = '', 
                        status = '', )
                    ]
            )
        else:
            return ApiV1EventsBatchPost200Response(
        )
        """

    def testApiV1EventsBatchPost200Response(self):
        """Test ApiV1EventsBatchPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
