apiVersion: v1
kind: Service
metadata:
  name: api-gateway-canary
  labels:
    app: api-gateway
    track: canary
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: api-gateway
    track: canary
  ports:
    - port: 80
      targetPort: 8080
