apiVersion: apps/v1
kind: Deployment
metadata:
  name: yosai-dashboard-canary
  labels:
    app: yosai-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yosai-dashboard
      track: canary
  template:
    metadata:
      labels:
        app: yosai-dashboard
        track: canary
    spec:
      containers:
        - name: yosai-dashboard
          image: yosai-intel-dashboard:latest
          ports:
            - containerPort: 8050
          env:
            - name: YOSAI_ENV
              value: "production"
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "yosai_intel"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yosai-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: yosai-secrets
                  key: SECRET_KEY
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /
              port: 8050
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8050
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
