apiVersion: apps/v1
kind: Deployment
metadata:
  name: yosai-dashboard-canary
  labels:
    app: yosai-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yosai-dashboard
      track: canary
  template:
    metadata:
      labels:
        app: yosai-dashboard
        track: canary
    spec:
      initContainers:
        - name: setup-symlinks
          image: yosai-intel-dashboard:latest
          command: ["python", "scripts/create_symlinks.py"]
      containers:
        - name: yosai-dashboard
          image: yosai-intel-dashboard:latest
          ports:
            - containerPort: 8050
          env:
            - name: YOSAI_ENV
              value: "production"
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "yosai_intel"
            - name: DB_USER
              value: "postgres"
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_ADDR
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_TOKEN
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: PYTHONPATH
              value: "/app:/app/yosai_intel_dashboard/src"
            - name: ENABLE_LEGACY_IMPORTS
              valueFrom:
                configMapKeyRef:
                  name: dashboard-config
                  key: ENABLE_LEGACY_IMPORTS
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8050
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8050
            initialDelaySeconds: 20
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8050
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
