apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
    - path: /metrics
      targetPort: 8001
