apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-ingestion-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: event-ingestion
  endpoints:
    - path: /metrics
      targetPort: 8000
