# Template for canary deployment using Istio weight-based routing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example_service-stable
  labels:
    app: example_service
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example_service
      track: stable
  template:
    metadata:
      labels:
        app: example_service
        track: stable
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: example_service
          image: example:${IMAGE_TAG:-v0.1.0}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example_service-canary
  labels:
    app: example_service
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example_service
      track: canary
  template:
    metadata:
      labels:
        app: example_service
        track: canary
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: example_service
          image: example:${CANARY_IMAGE_TAG:-v0.1.0}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example_service
spec:
  host: example_service
  subsets:
    - name: stable
      labels:
        track: stable
    - name: canary
      labels:
        track: canary
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example_service
spec:
  hosts:
    - example_service
  http:
    - route:
        - destination:
            host: example_service
            subset: stable
          weight: 90
        - destination:
            host: example_service
            subset: canary
          weight: 10
