# DestinationRule example enabling mTLS between services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example_service
  namespace: yosai-dev
spec:
  host: example_service.yosai-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
