apiVersion: apps/v1
kind: Deployment
metadata:
  name: yosai-dashboard
  namespace: yosai-dev
  labels:
    app: yosai-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yosai-dashboard
  template:
    metadata:
      labels:
        app: yosai-dashboard
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: setup-symlinks
          image: yosai-intel-dashboard:${IMAGE_TAG:-v0.1.0}
          imagePullPolicy: IfNotPresent
          command: ["python", "scripts/create_symlinks.py"]
      containers:
        - name: yosai-dashboard
          image: yosai-intel-dashboard:${IMAGE_TAG:-v0.1.0}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
          env:
            - name: PYTHONPATH
              value: "/app:/app/yosai_intel_dashboard/src"
            - name: ENABLE_LEGACY_IMPORTS
              value: "true"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8050
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8050
            initialDelaySeconds: 20
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8050
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
