apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: yosai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:1.21.0
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: ""
            - name: POOL_MODE
              value: session
          ports:
            - containerPort: 6432
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: yosai-dev
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
      targetPort: 6432
