apiVersion: v1
kind: Secret
metadata:
  name: yosai-secrets
  namespace: yosai-dev
type: Opaque
stringData:
  # Values are populated by the deployment pipeline. Do not store real
  # secrets in version control.
  AUTH0_CLIENT_ID: "<managed-secret>"
  AUTH0_CLIENT_SECRET: "<managed-secret>"
  KAFKA_USERNAME: "<managed-secret>"
  KAFKA_PASSWORD: "<managed-secret>"
