apiVersion: v1
kind: ServiceAccount
metadata:
  name: yosai-dashboard
  namespace: yosai-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yosai-dashboard-role
  namespace: yosai-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yosai-dashboard-binding
  namespace: yosai-dev
subjects:
  - kind: ServiceAccount
    name: yosai-dashboard
    namespace: yosai-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yosai-dashboard-role
