apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: yosai-dashboard.yosai-dev.svc.cluster.local
  namespace: yosai-dev
spec:
  routes:
    - name: GET /api
      condition:
        method: GET
        pathRegex: "/api/.*"
      isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
