apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: yosai-dashboard-split
  namespace: yosai-dev
spec:
  service: yosai-dashboard
  backends:
    - service: yosai-dashboard-v1
      weight: 90
    - service: yosai-dashboard-v2
      weight: 10
