name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job: [python, go, migration]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        if: matrix.job == 'python' || matrix.job == 'migration'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Go
        if: matrix.job == 'go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Python deps
        if: matrix.job == 'python' || matrix.job == 'migration'
        run: |
          pip install -r requirements.lock
          pip install -r requirements-test.txt
      - name: Run Python tests
        if: matrix.job == 'python'
        run: |
          pytest --cov=./ --cov-report=xml -q
      - name: Upload coverage
        if: matrix.job == 'python'
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: coverage.xml
      - name: Run Go tests
        if: matrix.job == 'go'
        working-directory: ./gateway
        run: go test ./...
      - name: Run migration tests
        if: matrix.job == 'migration'
        run: pytest tests/migration tests/test_migrations.py -q
  container-build:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

