name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Run tests
        run: pytest -q

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run Go tests
        run: go test ./...

  migration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Run migration tests
        run: pytest tests/test_migrations.py -q

  container-build:
    runs-on: ubuntu-latest
    needs: [python-tests, go-tests, migration-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t yosai-intel .
