name: Daily Container Scan

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  daily-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.64.1
          cache: true
      - name: Scan latest images
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 ghcr.io/${{ github.repository }}-gateway:latest
          trivy image --severity HIGH,CRITICAL --exit-code 1 ghcr.io/${{ github.repository }}-analytics:latest
          trivy image --severity HIGH,CRITICAL --exit-code 1 ghcr.io/${{ github.repository }}-event-ingestion:latest
