name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: echo "building"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: yosai-dashboard:${{ github.sha }}
      MIGRATION_STATE: head
    steps:
      - uses: actions/checkout@v5
      - name: Deploy
        run: echo "deploying"
      - name: Record rollback state
        run: |
          mkdir -p deployment
          echo '{"image": "'${IMAGE_TAG}'", "migration": "'${MIGRATION_STATE}'"}' > deployment/rollback_state.json
      - uses: actions/upload-artifact@v3
        with:
          name: rollback-state
          path: deployment/rollback_state.json

  rollback:
    if: failure()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v3
        with:
          name: rollback-state
          path: deployment
      - name: Run rollback
        run: deployment/scripts/rollback.sh
