name: Dev container smoke
on:
  pull_request:
    branches: ["**"]
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build API dev image
        run: docker build -f docker/Dockerfile.dev -t yosai-dev:pr .
      - name: Run container
        run: docker run -d --name yosai-dev -p 8000:8000 -e SECRET_KEY=test -e ENABLE_METRICS=0 yosai-dev:pr
      - name: Wait for health
        run: |
          for i in $(seq 1 60); do
            curl -sf http://localhost:8000/healthz && exit 0 || sleep 1
          done
          exit 1
      - name: Docs check
        run: curl -sSf http://localhost:8000/docs >/dev/null
      - name: Stop
        if: always()
        run: docker rm -f yosai-dev
