name: DevOps Lint
on: { push: {}, pull_request: {} }

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Hadolint (Dockerfiles)
        run: |
          set -euo pipefail
          files=("Dockerfile" "Dockerfile.gateway")
          for f in "${files[@]}"; do
            if [[ -f "$f" ]]; then
              echo "Linting $f"
              docker run --rm -i hadolint/hadolint < "$f"
            else
              echo "Skip $f (not found)"
            fi
          done
  devops-hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck curl
      - name: Run DevOps hygiene tests
        run: scripts/ci/test_devops_hygiene.sh
