name: DevOps Lint
on: { push: {}, pull_request: {} }

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          set -euo pipefail
          mapfile -t files < <(git ls-files '*.sh')
          if [ "${#files[@]}" -gt 0 ]; then shellcheck "${files[@]}"; else echo "No shell scripts found."; fi
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hadolint (Dockerfiles)
        run: |
          set -euo pipefail
          files=("Dockerfile" "Dockerfile.gateway")
          for f in "${files[@]}"; do
            if [[ -f "$f" ]]; then
              echo "Linting $f"
              docker run --rm -i hadolint/hadolint < "$f"
            else
              echo "Skip $f (not found)"
            fi
          done
