name: DevOps Lint
on: { push: {}, pull_request: {} }

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  devops-hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck curl
          curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o hadolint
          sudo install hadolint /usr/local/bin/hadolint
      - name: Run DevOps hygiene tests
        run: scripts/ci/test_devops_hygiene.sh
