name: Migration Check

on:
  pull_request:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.lock
      - run: python scripts/migrate.py --dry-run
      - name: Timescale migrations
        run: python scripts/migrate.py --config migrations/timescale/alembic.ini --dry-run
